# In the first case, x prints 3. In the second, it would return an error because x is only in the scope of the block.